#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK

import sys
import os
from localsql.localsql import LocalSQL

if __name__ == '__main__':
    try:
        LocalSQL().main()
    except EOFError:
        sys.exit(0)
